### ISSUE TITLE
__init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by blais** [beancount/beancount#291]
**[Original report](https://bitbucket.org/blais/beancount/issue/291) by Martin Michlmayr (Bitbucket: [tbm13](https://bitbucket.org/tbm13), GitHub: [tbm](https://github.com/tbm)).**

----------------------------------------

With current hg I get:

```
$ pip3 install .
Processing /home/tbm/scratch/cvs/beancount
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-w0vdqa0_-build/setup.py", line 170, in <module>
        shell=False, encoding='utf8').split()
      File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.5/subprocess.py", line 383, in run
        with Popen(*popenargs, **kwargs) as process:
    TypeError: __init__() got an unexpected keyword argument 'encoding'
```

**Comment by blais** [comment]
**Original comment by Martin Michlmayr (Bitbucket: [tbm13](https://bitbucket.org/tbm13), GitHub: [tbm](https://github.com/tbm)).**

----------------------------------------

This is with Python 3.5

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

Fixed #291: Python 3.5 doesn't support encoding in subprocess.

**Comment by blais** [comment]
**Original comment by Martin Michlmayr (Bitbucket: [tbm13](https://bitbucket.org/tbm13), GitHub: [tbm](https://github.com/tbm)).**

----------------------------------------

Thanks, it works with Python 3.5 now!
