### PR TITLE
setup: fix gcc error

### PR DESCRIPTION
**Pull request by simonla**
beancount/parser/tokens.c:174:5:error: 'for' loop initial declaration used outside C99 mode

### CODE REVIEW

**Comment by blais** [comment]
We could change the code instead to put the variable declaration above

**Comment by dnicolodi** [comment]
@blais Do you know which compiler chokes on this? I guess it was working on your Ubuntu 16.04, thus it must be something older, and anything older than that does not come with Python 3.6, which we require.

**Comment by blais** [comment]
No idea, but I don't think moving the declarations up in the function for v2 would hurt anything if it helps someon

**Comment by dnicolodi** [comment]
I just would like to have a way to check if this is the only fix needed.

**Comment by blais** [comment]
Good point let's have users send a patch
