### ISSUE TITLE
A DisplayContext adjusted with set_fixed_precision cannot be applied with update_from

### ISSUE THREAD

**Issue by josephw** [beancount/beancount#968]
`mypy` is failing on `master` since 9e148b76216982ec93 with:

```
beancount/core/display_context.py:294: error: Incompatible types in assignment (expression has type "_FixedPrecisionContext", target has type "_CurrencyContext")  [assignment]
```

To fix this, `ccontexts` should probably become a `dict[str, _ContextBase]`, but making this change highlights that there's a potential bug in the current implementation. Adding a new test to `TestDisplayContext` of:

```
+    def test_set_fixed_precision_can_apply_to_update_from(self):
+        dcontext = display_context.DisplayContext()
+        dcontext2 = display_context.DisplayContext()
+
+        dcontext2.set_fixed_precision("A", 1)
+        dcontext.update_from(dcontext2)
+
```

fails with:
```
    def update_from(self, other: _CurrencyContext) -> None:
        super().update_from(other)
>       self.fractional_dist.update_from(other.fractional_dist)
E       AttributeError: '_FixedPrecisionContext' object has no attribute 'fractional_dist'. Did you mean: 'fractional_digits'?
```

because  `_CurrencyContext` assumes that it will only be updated with instances of `_CurrencyContext`.

I'm not sure what the correct behaviour is here; perhaps duplicating the `_FixedPrecisionContext`, rather than trying to mutate the existing `_CurrencyContext`? This was discovered looking into `mypy`, rather than an actual use case, so this may not be possible in practice.

**Comment by josephw** [comment]
This was closed in df4b77fe0ff7dd2, but I don't believe that's a full fix. The PR in #970 includes a test to demonstrate the remaining edge case, as well as an alternate fix.
