### ISSUE TITLE
Compilation error when building v3

### ISSUE THREAD

**Issue by mbkamble** [beancount/beancount#683]
This is my first attempt at building beancount v3. So the entirebuild flow, bazel etc. is completely new to me. Following the instructions in the Installing Beancount (v3) googledoc, I installed the latest version fo bazel (version 6.0.0-pre.20211019.1) and ran the build command on the default branch
The build fails with an error while compiling `gnulib/lib/c-stack.c`

Upon searching, it seems I am hitting this issue:  https://lists.gnu.org/archive/html/bug-m4/2021-03/msg00000.html
Else where I also got a clue that it is clashing with the define in `/usr/include/bits/sigstksz.h`
```
26:/* Default stack size for a signal handler: sysconf (SC_SIGSTKSZ).  */
27:# undef SIGSTKSZ
28:# define SIGSTKSZ sysconf (_SC_SIGSTKSZ)
```

But I have no clue how to resolve this. My linux distro is ClearLinux.

```
sh> bazel build //bin:all
INFO: Analyzed 14 targets (0 packages loaded, 0 targets configured).
INFO: Found 14 targets...
INFO: From CcConfigureMakeRule external/mpdecimal/mpdecimal/include:

INFO: From CcConfigureMakeRule third_party/parser/reflex/include:

ERROR: /home/mbkamble/.cache/bazel/_bazel_mbkamble/e2971710160b36005629c2cbd7fcfdca/external/m4_v1.4.18/gnulib/BUILD.bazel:192:11: Compiling gnulib/lib/c-stack.c [for host] failed: (Exit 1): cc failed: error executing command /usr/bin/cc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 25 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from /usr/include/signal.h:328,
                 from external/m4_v1.4.18/gnulib/lib/c-stack.c:49:
external/m4_v1.4.18/gnulib/lib/c-stack.c:55:26: error: missing binary operator before token "("
   55 | #elif HAVE_LIBSIGSEGV && SIGSTKSZ < 16384
      |                          ^~~~~~~~
external/m4_v1.4.18/gnulib/lib/c-stack.c:139:8: error: variably modified 'buffer' at file scope
  139 |   char buffer[SIGSTKSZ];
      |        ^~~~~~
ERROR: /home/mbkamble/opensource/beancount/beancount/cparser/BUILD:36:11 Middleman _middlemen/_S_Sbeancount_Scparser_Cparser_Uheaders-BazelCppSemantics_build_arch_k8-fastbuild failed: (Exit 1): cc failed: error executing command /usr/bin/cc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 25 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 166.782s, Critical Path: 61.16s
INFO: 177 processes: 6 internal, 171 linux-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by mbkamble** [comment]
After searching some more, I have root caused the problem. My distro (ClearLinux) has already moved to glibc version 2.34. m4 older than 1.4.19 fails to build with 2.34. So, rules_m4 specified in `third_party/parser/setup.bzl` which is sourced from https://github.com/jmillikin/rules_m4/ needs to be upgraded to support m4-1.4.19. There is already an open issue for that : https://github.com/jmillikin/rules_m4/issues/9
Seems it may take soem time for the version upgrade in rules_m4

Meanwhile, I would like to use flex, bison form my system installation instead of compiling them as part of the build process. Can anyone guide me how to configure bazel to use system binaries of flex and bison? `reflex` does not exist in my distro's packages. So I need to build it.

**Comment by blais** [comment]
I'm not sure what to add. Building with local flexm& bison might cause you other headaches.
I would try to help out make the upgrade to support newer m4. (I'm on 1.4.18 FWIW)

**Comment by mbkamble** [comment]
After riding the steep learning curve of bazel, I have been able to hack the .bzl files in third-party/parser and a couple of other files to change from using locally built `m4` and `bison` to the system-installed `bison`. For anyone wanting to use this hack temporarily until rules_m4 bumps up m4 version to 1.4.19, I have pushed my commit to `mbk_glibc2.34` branch on my fork at [github.com/mbkamble/beancount](https://github.com/mbkamble/beancount/tree/mbk_glibc2.34)
